---
# tasks file for osp.servers
- name: Create server instances
  os_server:
    cloud: "{{ __openstack_server.cloud }}"
    name:  "{{ __openstack_server.name }}"
    state: "{{ __openstack_server.state }}"
    image: "{{ __openstack_server.image }}"
    flavor: "{{ __openstack_server.flavor }}"
    key_name: "{{ __openstack_server.key_name }}"
    wait: true
    security_groups: "{{ __openstack_server.security_group }}"
    delete_fip: "{{ __openstack_server.delete_fip | default(true) }}"
    meta: "group={{ __openstack_server.meta.group }},deployment_name={{ __openstack_server.meta.deployment_name }}"
    nics:
      - net-name: int_network
    userdata: |
      #!/bin/bash
      curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
      cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
  loop: "{{ openstack_servers }}"      
  loop_control:
    loop_var: __openstack_server
  async: 900
  poll: 0

- name: Add floating IP to instances
  os_floating_ip:
    cloud: "{{ __openstack_server.cloud }}"
    state: "{{ __openstack_server.state }}"
    reuse: yes
    server: "{{ __openstack_server.name }}"
    network: ext_network
    wait: true
    timeout: 180
  loop: "{{ openstack_servers }}"
  loop_control:
    loop_var: __openstack_server
